<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Usuario extends \Entities\Usuario implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getCodUsuario()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["codUsuario"];
        }
        $this->__load();
        return parent::getCodUsuario();
    }

    public function setSenha($senha)
    {
        $this->__load();
        return parent::setSenha($senha);
    }

    public function getSenha()
    {
        $this->__load();
        return parent::getSenha();
    }

    public function setNome($nome)
    {
        $this->__load();
        return parent::setNome($nome);
    }

    public function getNome()
    {
        $this->__load();
        return parent::getNome();
    }

    public function setDtUltimoAcesso($dtUltimoAcesso)
    {
        $this->__load();
        return parent::setDtUltimoAcesso($dtUltimoAcesso);
    }

    public function getDtUltimoAcesso()
    {
        $this->__load();
        return parent::getDtUltimoAcesso();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setPapel($papel)
    {
        $this->__load();
        return parent::setPapel($papel);
    }

    public function getPapel()
    {
        $this->__load();
        return parent::getPapel();
    }

    public function setConjuntoSelecao($conjuntoSelecao)
    {
        $this->__load();
        return parent::setConjuntoSelecao($conjuntoSelecao);
    }

    public function getConjuntoSelecao()
    {
        $this->__load();
        return parent::getConjuntoSelecao();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'codUsuario', 'senha', 'nome', 'dtUltimoAcesso', 'email', 'papel', 'conjuntoSelecao');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}