<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Disciplina extends \Entities\Disciplina implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setCodDepto($codDepto)
    {
        $this->__load();
        return parent::setCodDepto($codDepto);
    }

    public function getCodDepto()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["codDepto"];
        }
        $this->__load();
        return parent::getCodDepto();
    }

    public function setNumDisciplina($numDisciplina)
    {
        $this->__load();
        return parent::setNumDisciplina($numDisciplina);
    }

    public function getNumDisciplina()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["numDisciplina"];
        }
        $this->__load();
        return parent::getNumDisciplina();
    }

    public function setCh($ch)
    {
        $this->__load();
        return parent::setCh($ch);
    }

    public function getCh()
    {
        $this->__load();
        return parent::getCh();
    }

    public function setNome($nome)
    {
        $this->__load();
        return parent::setNome($nome);
    }

    public function getNome()
    {
        $this->__load();
        return parent::getNome();
    }

    public function setDepartamento(\Entities\Departamento $departamento = NULL)
    {
        $this->__load();
        return parent::setDepartamento($departamento);
    }

    public function getDepartamento()
    {
        $this->__load();
        return parent::getDepartamento();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'codDepto', 'numDisciplina', 'ch', 'nome', 'departamento');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}