<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Correspondencia extends \Entities\Correspondencia implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setCodCompCurric($codCompCurric)
    {
        $this->__load();
        return parent::setCodCompCurric($codCompCurric);
    }

    public function getCodCompCurric()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["codCompCurric"];
        }
        $this->__load();
        return parent::getCodCompCurric();
    }

    public function setCodCompCurricCorresp($codCompCurricCorresp)
    {
        $this->__load();
        return parent::setCodCompCurricCorresp($codCompCurricCorresp);
    }

    public function getCodCompCurricCorresp()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["codCompCurricCorresp"];
        }
        $this->__load();
        return parent::getCodCompCurricCorresp();
    }

    public function setPercentual($percentual)
    {
        $this->__load();
        return parent::setPercentual($percentual);
    }

    public function getPercentual()
    {
        $this->__load();
        return parent::getPercentual();
    }

    public function setComponenteCurricular(\Entities\ComponenteCurricular $componenteCurricular = NULL)
    {
        $this->__load();
        return parent::setComponenteCurricular($componenteCurricular);
    }

    public function getComponenteCurricular()
    {
        $this->__load();
        return parent::getComponenteCurricular();
    }

    public function setComponenteCurricularCorresp(\Entities\ComponenteCurricular $componenteCurricularCorresp = NULL)
    {
        $this->__load();
        return parent::setComponenteCurricularCorresp($componenteCurricularCorresp);
    }

    public function getComponenteCurricularCorresp()
    {
        $this->__load();
        return parent::getComponenteCurricularCorresp();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'codCompCurric', 'codCompCurricCorresp', 'percentual', 'componenteCurricular', 'componenteCurricularCorresp');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}